{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.configmap_etc }}
{{- $envAll := . }}

{{- if empty .Values.conf.dmapi.keystone_authtoken.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.dmapi.keystone_authtoken "auth_uri" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.dmapi.keystone_authtoken "auth_url" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dmapi.region_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dmapi.project_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dmapi.project_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dmapi.user_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "username" .Values.endpoints.identity.auth.dmapi.username -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "password" .Values.endpoints.identity.auth.dmapi.password -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.memcached_servers -}}
{{- $_ := tuple "oslo_cache" "internal" "memcache" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" | set .Values.conf.dmapi.keystone_authtoken "memcached_servers" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.keystone_authtoken.memcache_secret_key -}}
{{- $_ := set .Values.conf.dmapi.keystone_authtoken "memcache_secret_key" ( default ( randAlphaNum 64 ) .Values.endpoints.oslo_cache.auth.memcache_secret_key ) -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.database.connection -}}
{{- $_ := tuple "oslo_db" "internal" "dmapi" "mysql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" | set .Values.conf.dmapi.database "connection" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.DEFAULT.transport_url -}}
{{- $_ := tuple "oslo_messaging" "internal" "triliovault" "amqp" . | include "helm-toolkit.endpoints.authenticated_transport_endpoint_uri_lookup" | set .Values.conf.dmapi.DEFAULT "transport_url" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dmapi.service_credentials "auth_url" -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.region_name -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "region_name" .Values.endpoints.identity.auth.dmapi.region_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.project_name -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "project_name" .Values.endpoints.identity.auth.dmapi.project_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.project_domain_name -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "project_domain_name" .Values.endpoints.identity.auth.dmapi.project_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.user_domain_name -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "user_domain_name" .Values.endpoints.identity.auth.dmapi.user_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.username -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "username" .Values.endpoints.identity.auth.dmapi.username -}}
{{- end -}}

{{- if empty .Values.conf.dmapi.service_credentials.password -}}
{{- $_ := set .Values.conf.dmapi.service_credentials "password" .Values.endpoints.identity.auth.dmapi.password -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.workloadmgr.keystone_authtoken "auth_uri" -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | set .Values.conf.workloadmgr.keystone_authtoken "auth_url" -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dmapi.region_name -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dmapi.project_name -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "admin_tenant_name" .Values.endpoints.identity.auth.dmapi.project_name -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dmapi.project_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dmapi.user_domain_name -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "username" .Values.endpoints.identity.auth.dmapi.username -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "admin_user" .Values.endpoints.identity.auth.dmapi.username -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "password" .Values.endpoints.identity.auth.dmapi.password -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "admin_password" .Values.endpoints.identity.auth.dmapi.password -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.memcached_servers -}}
{{- $_ := tuple "oslo_cache" "internal" "memcache" . | include "helm-toolkit.endpoints.host_and_port_endpoint_uri_lookup" | set .Values.conf.workloadmgr.keystone_authtoken "memcached_servers" -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.keystone_authtoken.memcache_secret_key -}}
{{- $_ := set .Values.conf.workloadmgr.keystone_authtoken "memcache_secret_key" ( default ( randAlphaNum 64 ) .Values.endpoints.oslo_cache.auth.memcache_secret_key ) -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.DEFAULT.sql_connection -}}
{{- $_ := tuple "oslo_db_wlm" "internal" "wlm" "mysql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" | set .Values.conf.workloadmgr.DEFAULT "sql_connection" -}}
{{- end -}}

{{- if empty .Values.conf.workloadmgr.DEFAULT.transport_url -}}
{{- $_ := tuple "oslo_messaging" "internal" "triliovault" "amqp" . | include "helm-toolkit.endpoints.authenticated_transport_endpoint_uri_lookup" | set .Values.conf.workloadmgr.DEFAULT "transport_url" -}}
{{- end -}}

{{- if empty .Values.conf.datamover.dmapi_database.connection -}}
{{- $_ := tuple "oslo_db" "internal" "dmapi" "mysql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" | set .Values.conf.datamover.dmapi_database "connection" -}}
{{- end -}}

{{- if empty .Values.conf.datamover.DEFAULT.dmapi_transport_url -}}
{{- $_ := tuple "oslo_messaging" "internal" "triliovault" "amqp" . | include "helm-toolkit.endpoints.authenticated_transport_endpoint_uri_lookup" | set .Values.conf.datamover.DEFAULT "dmapi_transport_url" -}}
{{- end -}}

{{- if and (empty .Values.conf.logging.handler_fluent) (has "fluent" .Values.conf.logging.handlers.keys) -}}
{{- $fluentd_host := tuple "fluentd" "internal" $envAll | include "helm-toolkit.endpoints.hostname_namespaced_endpoint_lookup" }}
{{- $fluentd_port := tuple "fluentd" "internal" "service" $envAll | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{- $fluent_args := printf "('%s.%s', '%s', %s)" .Release.Namespace .Release.Name $fluentd_host $fluentd_port }}
{{- $handler_fluent := dict "class" "fluent.handler.FluentHandler" "formatter" "fluent" "args" $fluent_args -}}
{{- $_ := set .Values.conf.logging "handler_fluent" $handler_fluent -}}
{{- end -}}

{{- if and (empty .Values.conf.logging.formatter_fluent) (has "fluent" .Values.conf.logging.formatters.keys) -}}
{{- $formatter_fluent := dict "class" "oslo_log.formatters.FluentFormatter" -}}
{{- $_ := set .Values.conf.logging "formatter_fluent" $formatter_fluent -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: dmapi-etc
type: Opaque
data:
  dmapi.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.dmapi | b64enc }}
  datamover.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.datamover | b64enc }}
  workloadmgr.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.workloadmgr | b64enc }}
  logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | b64enc }}
  api-paste.ini: {{ include "helm-toolkit.utils.to_ini" .Values.conf.paste | b64enc }}
  alembic.ini: {{ include "helm-toolkit.utils.to_ini" .Values.conf.alembic | b64enc }}
  triliovault-object-store.conf: {{ include "helm-toolkit.utils.to_ini" .Values.conf.triliovault_object_store | b64enc }}
  fuse.conf: {{ .Values.conf.fuse | b64enc }}
  s3cert: {{ .Values.conf.s3cert | default "" | b64enc }}
{{- end }}
